"""Runtime adapters migrated from the legacy monolith."""

from .input_discovery import (
    DiscoveredRuntimeInputs,
    InputFileMeta,
    build_input_basename,
    classify_source_type,
    discover_input_file,
    discover_runtime_inputs,
    parse_filename_composition,
    parse_filename_load,
    parse_filename_sweep,
    summarize_discovered_inputs,
)
from .labview_reader import (
    LabviewReadResult,
    choose_labview_sheet,
    list_sheet_names_xlsx,
    read_labview_xlsx,
    summarize_labview_read,
)
from .kibox_reader import (
    KiboxAggregateResult,
    KiboxReadResult,
    aggregate_kibox_mean,
    read_kibox_csv,
    summarize_kibox_aggregate,
    summarize_kibox_read,
)
from .motec_reader import (
    MotecReadResult,
    read_motec_csv,
    summarize_motec_read,
)
from .open_to_csv import (
    DEFAULT_OPENTOCSV_CANDIDATES,
    PIPELINE_RESULT_SUFFIX,
    ExportRequest,
    ExportResult,
    build_output_name,
    default_open_to_csv_settings_path,
    export_open_file,
    export_open_inputs,
    export_open_paths,
    find_open_to_csv_path,
    planned_pipeline_csv_name,
    planned_pipeline_csv_path,
    summarize_export_results,
)

__all__ = [
    "DiscoveredRuntimeInputs",
    "DEFAULT_OPENTOCSV_CANDIDATES",
    "InputFileMeta",
    "KiboxAggregateResult",
    "KiboxReadResult",
    "LabviewReadResult",
    "MotecReadResult",
    "PIPELINE_RESULT_SUFFIX",
    "ExportRequest",
    "ExportResult",
    "aggregate_kibox_mean",
    "build_input_basename",
    "build_output_name",
    "classify_source_type",
    "default_open_to_csv_settings_path",
    "discover_input_file",
    "discover_runtime_inputs",
    "export_open_file",
    "export_open_inputs",
    "export_open_paths",
    "find_open_to_csv_path",
    "list_sheet_names_xlsx",
    "parse_filename_composition",
    "parse_filename_load",
    "parse_filename_sweep",
    "planned_pipeline_csv_name",
    "planned_pipeline_csv_path",
    "read_kibox_csv",
    "read_labview_xlsx",
    "read_motec_csv",
    "summarize_kibox_aggregate",
    "summarize_kibox_read",
    "summarize_discovered_inputs",
    "summarize_labview_read",
    "summarize_motec_read",
    "summarize_export_results",
    "choose_labview_sheet",
]
