schema_version = 1

[metadata]
"format" = "pipeline29_text"
"schema_version" = 1
"updated_at_utc" = "2026-06-28T14:01:51+00:00"
"source_kind" = "text"
"source_path" = "E:\\Mestrado\\Pipeline_Newgen\\config\\pipeline29_text"
