"""Constants for the time_diagnostics stage.

Ported from nanum_pipeline_29.py lines 104-112.
"""

from __future__ import annotations


TIME_DELTA_ERROR_THRESHOLD_S = 1.2
TIME_DELTA_PLOT_YMIN_S = 0.8
TIME_DELTA_PLOT_YMAX_S = 1.6
TIME_DELTA_PLOT_YSTEP_S = 0.1

DEFAULT_MAX_DELTA_BETWEEN_SAMPLES_MS = 1200.0
DEFAULT_MAX_ACT_CONTROL_ERROR_C = 5.0
DEFAULT_MAX_ECT_CONTROL_ERROR_C = 2.0

TIME_DIAG_PLOT_DPI = 150
TIME_DIAG_FILE_SCATTER_MAX_POINTS = 200
